language:
- c
os:
- osx
- linux
compiler:
- clang
- gcc
script: travis_wait 60 make all
stages:
  - test
  - spike
  - name: deploy
    if: branch = master AND type = push AND fork = false
  - name: run
    if: branch = master AND type = push AND fork = false
jobs:
  include:
    - stage: spike
      sudo: required
      services: docker
      os: linux
      script:
        - docker build -t joanbm/selfie32 .
        - docker run joanbm/selfie32 make spike
    - stage: deploy
      sudo: required
      services: docker
      os: linux
      script:
        - docker build -t joanbm/selfie32 .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push joanbm/selfie32
    - stage: run
      sudo: required
      services: docker
      os: linux
      script:
        - docker run joanbm/selfie32 make spike