# builder image
FROM ubuntu:16.04 AS builder

# specify work directory and RISC-V install directory
ENV TOP /opt
ENV RISCV $TOP/riscv
ENV PATH $PATH:$RISCV/bin

# use multiple cores to speed up compilation
ENV MAKEFLAGS -j4

WORKDIR $TOP

# install tools to build RISC-V gnu toolchain, spike, pk and qemu
RUN apt-get update && apt-get install -y \
  autoconf \
  automake \
  autotools-dev \
  curl \
  device-tree-compiler \
  libmpc-dev \
  libmpfr-dev \
  libgmp-dev \
  libusb-1.0-0-dev \
  gawk \
  build-essential \
  bison \
  flex \
  texinfo \
  gperf \
  libtool \
  patchutils \
  bc \
  zlib1g-dev \
  device-tree-compiler \
  pkg-config \
  libexpat-dev \
  git \
  gcc \
  python \
  libglib2.0-dev

# get sources from HEAD
# FIXME: This clones not only the required code for the build, but also the entire history,
# so it requires a lot of bandwidth, resources and time.
# it would be better to do something like a shallow clone (like git's --depth 1),
# but unfortunately, as of 20190117, there isn't any solid way to do this
RUN git clone https://github.com/riscv/riscv-tools.git \
  && cd riscv-tools \
  && git submodule update --init --recursive

# build most of the toolkit with gcc, including spike and pk
RUN mkdir -p $RISCV \
  && cd riscv-tools \
  && CC=gcc CXX=g++ ./build.sh

# additionally, build qemu
RUN cd riscv-tools/riscv-gnu-toolchain && \
	./configure --prefix=$RISCV && \
	make build-qemu

# test the RISC-V gnu toolchain
RUN echo '#include <stdio.h>\n int main(void) { printf("Hello world!\\n"); return 0; }' > hello.c \
  && riscv64-unknown-elf-gcc -o hello hello.c \
  && spike pk hello \
  && qemu-riscv64 hello

# remove RISC-V gnu toolchain to shrink image size
 RUN rm -rf \
    riscv/bin/riscv64-* \
    riscv/bin/openocd \
    riscv/lib/gcc \
    riscv/libexec \
    riscv/share

# release image
FROM ubuntu:16.04

# specify work directory and RISC-V install directory
ENV TOP /opt
ENV RISCV $TOP/riscv
ENV PATH $PATH:$RISCV/bin

WORKDIR $TOP

# install gcc, make and diff
RUN apt-get update && apt-get install -y \
    device-tree-compiler \
    build-essential \
    gcc \
    libglib2.0-dev \
  && rm -rf /var/lib/apt/lists/*

# copy spike, pk and qemu from builder image
COPY --from=builder $RISCV/ $RISCV/